version: "3"

services:

  freeswitch-exe:
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch
    environment:
      - AWS_BUCKET=freeswitch-store-test
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_ID=AKIAWPR7EWCGLB3UNPDH
      - AWS_SECRET_KEY=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
      - DOMAIN=54.183.111.203
      - FINN=http://54.183.111.203:3001
      - FREESWITCH=http://54.183.111.203:3000
      - AFFINITY=Freeswitch
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/freeswitch/google_key.json
      - PATH=/usr/local/freeswitch/bin:$PATH
    ports:
      - "5060:5060"
      - "5061:5061"
      - "5060:5060/udp"
      - "5061:5061/udp"
      - "5080:5080"
      - "5081:5081"
      - "5080:5080/udp"
      - "5081:5081/udp"
      - "6060:6060"
      - "6061:6061"
      - "6060:6060/udp"
      - "6061:6061/udp"
      - "16384-16394:16384-16394/udp"
      - "8080:8080"
    volumes:
      - .:/api
      - ../S3:/opt/S3 # fake store
      - ./freeswitch_configuration/conf:/opt/freeswitch/conf
      - ./freeswitch_configuration/db:/opt/freeswitch/db
      - ./freeswitch_configuration/log:/opt/freeswitch/log
      - ./freeswitch_configuration/scripts:/opt/freeswitch/scripts
      - ./freeswitch_configuration/store:/opt/freeswitch/store
      - ./freeswitch_tmp:/tmp
    command: freeswitch -nonat -conf /usr/local/freeswitch/conf -log /usr/local/freeswitch/log -db /usr/local/freeswitch/db -scripts /usr/local/freeswitch/scripts -storage /usr/local/freeswitch/store
    depends_on:
      - web

  web:
    environment:
      - AWS_BUCKET=freeswitch-store-test
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_ID=AKIAWPR7EWCGLB3UNPDH
      - AWS_SECRET_KEY=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
      - DOMAIN=54.183.111.203
      - FINN=http://54.183.111.203:3001
      - FREESWITCH=http://54.183.111.203:3000
      - AFFINITY=Freeswitch
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/freeswitch/google_key.json
      - PATH=/usr/local/freeswitch/bin:$PATH
    volumes:
      - ./freeswitch_configuration/store:/opt/freeswitch/store
      - ./freeswitch_tmp:/tmp
      - .:/api
      - ../S3:/opt/S3 # fake store
    command: vendor/wait-for-it.sh -t 0 192.168.59.70:5672 -- bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
#    command: rails server -b '0.0.0.0'
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch-web
    depends_on:
      - cassandra
      - rabbitmq
    ports:
      - "3000:3000"

#   finn:
# #    build: /($dirname 'pwd')/finn-rails-api/
#     environment:
#       RAILS_ENV: development
#       HOST_AND_PORT: http://localhost:3000
#       METASWITCH_MAILBOX_ROOT: https://192.91.191.51:5145
#       METASWITCH_PROVISION_ROOT: https://192.91.191.51:7901
#       METASWITCH_NOTIFICATION_ROOT: https://b2bgw-test.spark.co.nz/spark/visualvoicemail
#       DEFAULT_LANGUAGE_CODE: en-US
#       CLASSIFIER_ENDPOINT: http://classifier:8501/v1/models/urgency_classifier:predict
#       AFFINITY: Metaswitch
#       GOOGLE_FIREBASE_CREDENTIALS_FILENAME: config/firebase_key.json
#       TRUSTED_DEPLOYMENT: 'false'
#       KEY_PATH: config/finn_false.key
#       CERTIFICATE_PATH: config/finn_false.pem
#       CA_PATH: config/finn_false_ca.pem
#       DOMAIN: '192.168.59.70'
#       GOOGLE_PROJECT_ID: finn-268607
#       GOOGLE_TRANSCRIPTION_BUCKET: sparkvoicemail-recordings
# #    command: vendor/wait-for-it.sh -t 0 192.168.59.70:5672 -- bash -c "rm -f tmp/pids/server.pid && service cron start && bundle exec rails server -b '0.0.0.0'"
#     command: "bundle exec rails server -b '0.0.0.0'"
#     image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch-api:latest
#     volumes:
#       - /($dirname 'pwd')/finn-rails-api/
#       - /($pwd)/vendor
#     ports:
#       - "3001:3000"
#     depends_on:
#       - cassandra


  cassandra:
    # image: cassandra:3.11.3
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch-cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ../finn-rails-api/out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  rabbitmq:
    # image: rabbitmq:management
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch-rabbitmq
    command: rabbitmq-server
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmqctl eval '{ true, rabbit_app_booted_and_running } = { rabbit:is_booted(node()), rabbit_app_booted_and_running }, { [], no_alarms } = { rabbit:alarms(), no_alarms }, [] /= rabbit_networking:active_listeners(), rabbitmq_node_is_healthy.' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  freeswitch_sneakers:
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/freeswitch-sneakers
#    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/frees
  #  volumes:	
#      - .:/app
    environment:
      - AWS_BUCKET=freeswitch-store-test
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_ID=AKIAWPR7EWCGLB3UNPDH
      - AWS_SECRET_KEY=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
      - DOMAIN=54.183.111.203
      - FINN=http://54.183.111.203:3001
      - FREESWITCH=http://54.183.111.203:3000
      - AFFINITY=Freeswitch
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/freeswitch/google_key.json
      - PATH=/usr/local/freeswitch/bin:$PATH
#    command: ./vendor/wait-for-it.sh -t 0 192.168.59.70:5672 -- bundle exec rails sneakers:run
    command: /api/vendor/wait-for-it.sh -t 0 192.168.59.70:5672 -- bundle exec rails sneakers:run
#    healthcheck:
#      test: "[ '0' -ne `lsof -i :amqp | wc -l` ] || exit 1"

