version: "3"

services:
  # in a deployment, the freeswitch exe and the api need to be co-located. We fake that
  # here by giving the required volumes to both containers
  # freeswitch deposits in /opt/freeswitch/store
  # the api deposits in /tmp


  freeswitch-exe:
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/test-frees:latest
#    env_file:
#      - .env-fs.production
    environment:
       - AWS_BUCKET=freeswitch-store-test
       - AWS_REGION=ap-southeast-2
       - AWS_ACCESS_ID=AKIAWPR7EWCGLB3UNPDH
       - AWS_SECRET_KEY=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
       - FREESWITCH_PUBLIC_IP=52.65.157.164
       - DOMAIN=172.31.10.6
       - FINN=http://172.31.10.6:3001
       - FREESWITCH=http://172.31.10.6:3000
       - AIDA=http://172.31.10.6:8085
       - AFFINITY=Freeswitch
       - GOOGLE_APPLICATION_CREDENTIALS=/usr/local/freeswitch/freeswitch-api-7867f30c80d7.json
       - PATH=/usr/local/freeswitch/bin:$PATH
       - MOD_AAI_TRANSCRIPTION_TOKEN=2a614e3febad4b05a56bc682c29a81ba
       - MOD_AUDIO_AAI_BUFFER_SECS=2
       - MOD_AAI_TRANSCRIPTION_FRAME_SIZE=10
       - MOD_AAI_TRANSCRIPTION_SERVICE_THREADS=2
    ports:
      - "6065:6065"
      - "6066:6066"
      - "6065:6065/udp"
      - "6066:6066/udp"
      - "5080:5080"
      - "5081:5081"
      - "5080:5080/udp"
      - "5081:5081/udp"
      - "6060:6060"
      - "6061:6061"
      - "6060:6060/udp"
      - "6061:6061/udp"
      - "16384-16394:16384-16394/udp"
      - "8080:8080"

    # command: freeswitch -nonat -conf /opt/freeswitch/conf -log /opt/freeswitch/log -db /opt/freeswitch/db -scripts /opt/freeswitch/scripts -storage /opt/freeswitch/store
#    command: freeswitch
    command:  freeswitch -nonat -conf /usr/local/freeswitch/conf -log /usr/local/freeswitch/log -db /usr/local/freeswitch/db -scripts /usr/local/freeswitch/scripts -storage /usr/local/freeswitch/store
    # depends_on:
    #   - web




  app:
    image: 445735284876.dkr.ecr.us-west-1.amazonaws.com/aida-au-prod:latest
    env_file:
      - .env-aida.au

    ports:
      - '8085:8085'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8085"]

