name: Deploy to Amazon ECS

on:
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f ./docker-build/Dockerfile.AWS.additional.modules  -t 445735284876.dkr.ecr.us-west-1.amazonaws.com/frees-azure .
          docker push 445735284876.dkr.ecr.us-west-1.amazonaws.com/frees-azure:$IMAGE_TAG
          echo "::set-output name=image::445735284876.dkr.ecr.us-west-1.amazonaws.com/frees-azure:$IMAGE_TAG"  
        
